### ISSUE TITLE
NotImplementedError: Platform does not define a GLUT font retrieval function

### ISSUE THREAD

**Issue by artificialhumanbeing** [eth-siplab/AvatarPoser#11]
Hi ! When I run ` $ python main_test_avatarposer.py ` , got this error. I tried the solution in https://github.com/MPI-IS/mesh/issues/49#issuecomment-705194582 , but it didn't work. Can someone help me with this error?
![image](https://user-images.githubusercontent.com/112940276/198206119-50f9bd6d-f884-4a23-a356-fad33012fdf9.png)

Thanks!

**Comment by ChrisGoettfert** [comment]
hey, how did you fix it?

**Comment by artificialhumanbeing** [comment]
> hey, how did you fix it?
Commented out the "GLUT" in "psbody/mesh/meshviewer.py ,line49", like `from OpenGL import GL, GLU #GLUT`
