### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by reynoldscem** [eth-siplab/AvatarPoser#2]
Hi,

It doesn't appear to be mentioned in your paper. Do you use any data augmentation during training? And if so, what is your procedure?

**Comment by jiaxi-jiang** [comment]
Hi, thanks for your interest in our work. We do not use any data augmentation during training, and all the details are provided in the code. Just tell me if you have any other questions.

**Comment by reynoldscem** [comment]
Thanks @jiaxi-jiang that's great. Very impressed with your project.
