### ISSUE TITLE
Input points for testing and training

### ISSUE THREAD

**Issue by Recialhot** [eth-siplab/AvatarPoser#26]
Testing and training are based on 3 points. I would like to change it to 5 points (adding points with two feet). Where should I modify it?

**Comment by jiaxi-jiang** [comment]
Hey, you can simply change the data preprocessing code in prepare_data.py to add also foot pose, and increase the number of inputs of the network

**Comment by Recialhot** [comment]
> 嘿，你可以简单地在prepare_data.py中更改数据预处理代码，以添加脚姿势，并增加网络的输入数量

when i use z to up, wherever x and y are facing, it will cause this:

![body_919](https://github.com/eth-siplab/AvatarPoser/assets/64907763/3d4091ea-6939-4ad4-9440-b6a257bc2075)


only when i use z to forward, x to left, y to up, it will cause this, but it not stand and Lifting feet is easy to fluctuate. when i see dataset_amass or your dataset_tracking, the data always z to up, but final result is right. my data z to up is not success. That's why? Thanks





Add a comment
Comment
 
Add your comment here...
 
Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests

Notifications
Customize
You’re receiving notifications because you authored the thread.
2 participants
![body_100](https://github.com/eth-siplab/AvatarPoser/assets/64907763/a025ad84-7c14-4e35-b988-2a9b78cf9f31)
