### ISSUE TITLE
miss dependences

### ISSUE THREAD

**Issue by YongtaoGe** [eth-siplab/AvatarPoser#4]
Hi authors. Thanks for your great work. 

When I try to train the model, I encountered the following error.  It would be helpful to provide the installation instructions to fix this bug. 

```
Traceback (most recent call last):
  File "main_train_avatarposer.py", line 16, in <module>
    from utils import utils_visualize as vis
  File "/AvatarPoser/utils/utils_visualize.py", line 8, in <module>
    from body_visualizer.tools.vis_tools import colors
ModuleNotFoundError: No module named 'body_visualizer'
```

**Comment by YongtaoGe** [comment]
The codebase also missed the 'generate_split.py' file.

**Comment by jiaxi-jiang** [comment]
Hi, thanks for your interest in our work.

The two packages are: https://github.com/nghorbani/body_visualizer and https://github.com/nghorbani/human_body_prior

Sorry I forget to upload the code for generating splitting - I will update and add more instructions later

**Comment by YongtaoGe** [comment]
@jiaxi-jiang Thanks for your kindly response.

**Comment by Wxyxixixi** [comment]
Hi seems there some error lies in body-visualizer package:

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/42725538/189480333-83d949c2-d148-4eb9-a9f6-383b68984786.png">

**Comment by jiaxi-jiang** [comment]
> Hi seems there some error lies in body-visualizer package:
> 
> <img alt="image" width="1092" src="https://user-images.githubusercontent.com/42725538/189480333-83d949c2-d148-4eb9-a9f6-383b68984786.png">

Hi, we observed the same problem before - you can just remove the if condition and make the code run this line https://github.com/mmatl/pyrender/blob/master/pyrender/mesh.py#L274

**Comment by Wxyxixixi** [comment]
> > Hi seems there some error lies in body-visualizer package:
> > <img alt="image" width="1092" src="https://user-images.githubusercontent.com/42725538/189480333-83d949c2-d148-4eb9-a9f6-383b68984786.png">
> 
> Hi, we observed the same problem before - you can just remove the if condition and make the code run this line https://github.com/mmatl/pyrender/blob/master/pyrender/mesh.py#L274

Hi, thanks for the quick reply! I wonder, will there be any harm if change the source code in pyrender directly? I found that by remove the face_color param in checker_mesh (https://github.com/eth-siplab/AvatarPoser/blob/71abcc6e60b599c3dc0148df26c4c8e0a951e937/utils/utils_visualize.py#L186) like this:
checker_mesh = trimesh.Trimesh(checker.v,checker.f,process=False), the code can be executed as well.
Just not sure if removing face_color will be any difference to the visualization result.

**Comment by jiaxi-jiang** [comment]
> > > Hi seems there some error lies in body-visualizer package:
> > > <img alt="image" width="1092" src="https://user-images.githubusercontent.com/42725538/189480333-83d949c2-d148-4eb9-a9f6-383b68984786.png">
> > 
> > 
> > Hi, we observed the same problem before - you can just remove the if condition and make the code run this line https://github.com/mmatl/pyrender/blob/master/pyrender/mesh.py#L274
> 
> Hi, thanks for the quick reply! I wonder, will there be any harm if change the source code in pyrender directly? I found that by remove the face_color param in checker_mesh (
> 
> https://github.com/eth-siplab/AvatarPoser/blob/71abcc6e60b599c3dc0148df26c4c8e0a951e937/utils/utils_visualize.py#L186
> 
> ) like this:
> checker_mesh = trimesh.Trimesh(checker.v,checker.f,process=False), the code can be executed as well.
> Just not sure if removing face_color will be any difference to the visualization result.

thanks for your suggestion. We will double check that.
