### ISSUE TITLE
Possible Typo in Code

### ISSUE THREAD

**Issue by Feiyu-Yao** [eth-siplab/AvatarPoser#5]
Hi jiaxi-jiang,

Your work AvatarPoser is excellent and it is kind that you can share your code in Github.
However, I found a possible typo in code. The preprocess.py saves processed data in ./data_fps60 while the dataroot is set to be ./data_cameraready_fps60 for training. I think these two should be the same.

Best
Feiyu

**Comment by jiaxi-jiang** [comment]
Hi Feiyu,

thank you very much for your interest in our work and the raised issue. Yes, they should be the same. Feel free to ask me if you have any other questions.

Best,
Jiaxi
